### ISSUE TITLE
Banned by mistake

### ISSUE THREAD

**Issue by KrakY-47** [ZeroTwo-Bot/anti-fish-lists#10]
Hi,
About 3 days ago i got banned by the bot from ZeroTwo support server by the reason that i sent phishing links( on memes channel) but i havent sent any links. All i did was replying to the scammer a message which is: "dissord-gift lol what kind of discord is that?" And right after i sent the message I got banned. I hope i made myself understood and I'id like to have my account unbanned from ZeroTwo support server.
Ty

**Comment by ByteAlex** [comment]
Please contact the staff team via email at appeal@zerotwo.bot to request an unban.
This repository is not supposed to be used for unban requests.
