### ISSUE TITLE
d1anes/d1xne taken down

### ISSUE THREAD

**Issue by Realswitzer** [ZeroTwo-Bot/anti-fish-lists#44]
The repository has been taken down by GitHub, along with account suspension so I assume it's safe to remove the URL.
`/blocklist.urls.json` line 28

I am aware there are more accounts doing similar things, like 6754-LGTM/d1xne/ which is a fork of the original. I am unsure if these are used to distribute Redline, or if it serves as a potential archive, but I would assume it's better to block it due to the potential for abuse.

**Comment by Realswitzer** [comment]
Adding to this, all of the /fastm31/* repos are down (account suspension).

**Comment by ByteAlex** [comment]
I think the GH repo links were primarily added by @DEVTomatoCake @JeDaYoshi . Can you confirm those are no longer an issue?

**Comment by JeDaYoshi** [comment]
yeah, it's safe to remove now I'd guess, GitHub deleted it as confirmed to them (and their support confirmed taking action in the account, as I reported it).

**Comment by Jerem584** [comment]
https://github.com/wxyn3/wxyn3 < new repo

**Comment by Realswitzer** [comment]
> https://github.com/wxyn3/wxyn3 < new repo

Line 30 and 31 block /wxyn3/wxyn3

> https://github.com/amoges2 < main acc where they download the actual virus.

Blocking it doesn't have a lot of purpose since it's the application and not the link being posted, but I guess adding it could help a bit.

**Comment by Realswitzer** [comment]
Closed with merge of #48

**Comment by Realswitzer** [comment]
nvm im dumb, wrong repo

**Comment by ByteAlex** [comment]
What exactly is the issue in this thread now?

**Comment by Realswitzer** [comment]
Closing, saw PR merged.
